#docker-compose -f zip.compose.yaml up --force-recreate --build -d
version: '3'
services:
  server-web-app:
    restart: always
    container_name: crc64.browser.toys
    build:
      dockerfile: crc64.dockerfile
      context: .
    environment:
      VIRTUAL_HOST: crc64.browser.toys
      LETSENCRYPT_HOST: crc64.browser.toys
      LETSENCRYPT_EMAIL: glen@glenmurphy.com

networks:
  default:
    external:
      name: nginx-proxy